name: "Setup conditionals"

permissions: {}

on:
  workflow_call:
    outputs:
      run-tests:
        description: "Whether to run heavyweight test jobs"
        value: ${{ jobs.config.outputs.run-tests }}
      is-prerelease:
        description: "Whether the PR has the prerelease label"
        value: ${{ jobs.config.outputs.is-prerelease }}

jobs:
  config:
    runs-on: ubuntu-latest
    outputs:
      run-tests: ${{ github.event_name != 'pull_request' || (github.event.action != 'closed' && github.event.pull_request.draft == false) }}
      is-prerelease: ${{ github.event_name == 'pull_request' && contains(github.event.pull_request.labels.*.name, 'prerelease') }}
    steps:
      - run: true
