name: "Convert (k8s)"

on:
  workflow_dispatch:
  pull_request:
    types: [labeled]

permissions:
  contents: read

defaults:
  run:
    shell: bash

env:
  HF_TOKEN: ${{ secrets.HF_TOKEN }}

jobs:
  convert:
    name: Convert (Qwen3-0.6B)
    runs-on: [lalamo-k8s]
    if: ${{ github.event_name == 'workflow_dispatch' || github.event.label.name == 'ci-k8s-test' }}

    steps:
      - uses: actions/checkout@v6
      - uses: ./.github/actions/setup

      - name: Convert model
        run: |
          lalamo convert "Qwen/Qwen3-0.6B"
