name: Test build and Check Distribution

on:
  pull_request:
    types: [closed]
    branches: [main]

permissions:
  contents: read
  id-token: write

jobs:
  test:
    name: build-and-optional-testpypi
    if: ${{ github.event.pull_request.merged == true && startsWith(github.event.pull_request.head.ref, 'bump/version-') }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version-file: pyproject.toml

      - uses: astral-sh/setup-uv@v6
        with:
          enable-cache: true

      - name: Build distributions
        run: uv build --no-sources

      - name: Check distributions with Twine
        run: uv run twine check dist/*
